### PR TITLE
schema modified after booking migration

### PR DESCRIPTION
**Pull request by nichohelmut**
added booking model, please review @vinitiet @DERNTOAN @hdittmar

### CODE REVIEW

**Review by DERNTOAN — CHANGES_REQUESTED** [review]
Model should contain 

belongs_to :user, through :bathroom

**Comment by nichohelmut** [comment]
added belongs_to :user, through: :bathroom @DERNTOAN @hdittmar  @vinitiet

**Review by DERNTOAN — APPROVED** [review]
all good

**Review by hdittmar — APPROVED** [review]
läuft

**Pull request merged**
